services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: gustave-roussey-backend:latest
    container_name: gustave-roussey-backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    ports:
      - "8080:8080"
    volumes:
      - backend_data:/app/database
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: gustave-roussey-frontend:latest
    container_name: gustave-roussey-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  backend_data:


networks:
  app-network:
    driver: bridge